name: Build and Publish Patched Dex

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      force_rebuild_tag:
        description: 'Пересобрать конкретный тег (например, v2.38.0)'
        required: false
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout self (для доступа к патчам)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Process upstream tags
        env:
          UPSTREAM_REPO: https://github.com/dexidp/dex.git
          TAG_SUFFIX: -oauth-domain-filter
          MIN_SUPPORTED_TAG: v2.40.0
        run: |
          set -e

          OWNER_LOWERCASE=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          DOCKER_IMAGE_NAME="ghcr.io/${OWNER_LOWERCASE}/dex${TAG_SUFFIX}"
          
          echo "Docker image name will be: $DOCKER_IMAGE_NAME"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          UPSTREAM_TAGS=$(git ls-remote --tags --refs $UPSTREAM_REPO | grep -o 'refs/tags/v[0-9].*' | sed 's#refs/tags/##' | grep -v '{}')

          if [ -n "${{ github.event.inputs.force_rebuild_tag }}" ]; then
              echo "Forcing rebuild for tag: ${{ github.event.inputs.force_rebuild_tag }}"
              UPSTREAM_TAGS="${{ github.event.inputs.force_rebuild_tag }}"
          fi

          for tag in $UPSTREAM_TAGS; do
            PATCHED_TAG="${tag}${TAG_SUFFIX}"

            if [ -z "${{ github.event.inputs.force_rebuild_tag }}" ] && git rev-parse -q --verify "refs/tags/${PATCHED_TAG}" >/dev/null; then
              echo "Tag ${PATCHED_TAG} already exists. Skipping."
              continue
            fi
            
            LATEST_VERSION=$(printf "%s\n%s" "$tag" "$MIN_SUPPORTED_TAG" | sort -V | tail -n 1)

            if [ "$LATEST_VERSION" != "$tag" ]; then
                echo "Skipping tag ${tag} as it is older than minimum supported version ${MIN_SUPPORTED_TAG}."
                continue
            fi

            echo "--- Processing tag: ${tag} ---"

            git clone --depth 1 --branch "$tag" $UPSTREAM_REPO source
            cd source

            echo "Applying patches..."
            git apply ../patches/*.patch

            echo "Building and pushing Docker image: ${DOCKER_IMAGE_NAME}:${tag}"
            docker buildx build . \
              --push \
              --tag "${DOCKER_IMAGE_NAME}:${tag}" \
              --tag "${DOCKER_IMAGE_NAME}:${tag%-*}"

            cd ..

            echo "Pushing new git tag ${PATCHED_TAG}"
            git commit --allow-empty -m "Build patched version for upstream tag ${tag}"
            git tag -a "${PATCHED_TAG}" -m "Release for ${tag}"
            git push origin "${PATCHED_TAG}"

            rm -rf source
          done
          
          echo "All new tags processed."
